spring.application.name=spring-boot-web-jpa-jsp

#DataSource configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=c##premsai
spring.datasource.password=prem123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#ServerConfiguration
server.port=9999
server.servlet.context-path=/easyshopping

#JpaConfiguration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#ViewResolverConfiguration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp